### ISSUE TITLE
Task: Upgrade to latest leanback

### ISSUE THREAD

**Issue by pfaffenrodt** [pfaffenrodt/android-object-adapter#2]
# Task

Upgrade to latest leanback.
Make diff with https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/leanback/leanback/src/main/java/androidx/leanback/widget/ObjectAdapter.java

latest version it has support for database [observables](https://developer.android.com/reference/android/database/Observable)

**Comment by michaeldonath** [comment]
Hey @pfaffenrodt , I'd like to work on this one!

**Comment by michaeldonath** [comment]
Hey @pfaffenrodt [ 'RecyclerView.Adapter'](https://android.googlesource.com/platform/frameworks/support/+/e096e4c/v7/recyclerview/src/android/support/v7/widget/RecyclerView.java) already implements the observable pattern. Your implementation already fits the latest version.
